
import { Permission } from '@/types/auth';

export const PERMISSION_LABELS: Record<Permission, string> = {
  'access_dashboard': 'Acessar Dashboard',
  'access_whatsapp': 'Acessar WhatsApp',
  'create_campaigns': 'Criar campanhas',
  'edit_campaigns': 'Editar campanhas',
  'view_templates': 'Visualizar templates',
  'send_messages': 'Enviar mensagens',
  'view_metrics': 'Visualizar métricas',
  'access_tasks': 'Acessar tarefas',
  'create_tasks': 'Criar tarefas',
  'assign_tasks': 'Atribuir tarefas a outros usuários',
  'finalize_tasks': 'Finalizar tarefas',
  'edit_execution_time': 'Editar tempo de execução',
  'access_calls': 'Acessar chamados',
  'create_calls': 'Criar chamados',
  'finalize_calls': 'Finalizar chamados',
  'link_calls_to_tasks': 'Vincular chamados a tarefas',
  'access_creatives': 'Acessar criativos',
  'create_edit_creatives': 'Criar/editar criativos',
  'approve_creatives': 'Aprovar criativos',
  'view_change_history': 'Ver histórico de alterações',
  'access_paid_media': 'Acessar Campanhas, Conjuntos e Anúncios',
  'create_campaigns_media': 'Criar campanhas',
  'view_metrics_media': 'Ver métricas',
  'access_reports': 'Acessar relatórios',
  'create_automatic_reports': 'Criar relatórios automáticos',
  'manage_user_settings': 'Gerenciar configurações do usuário',
  'manage_collaborators': 'Gerenciar colaboradores',
  'manage_whatsapp_templates': 'Gerenciar templates WhatsApp',
  'manage_api_settings': 'Gerenciar configurações de API',
  'manage_appearance_and_visual_identity': 'Gerenciar aparência e identidade visual',
  'manage_external_integrations': 'Gerenciar integrações externas',
  'manage_variables_and_pre_configurations': 'Gerenciar variáveis e pré-configurações',
  'view_billing_settings': 'Visualizar configurações de faturamento',
  'view_system_logs': 'Visualizar logs do sistema',
  'access_client_reports': 'Acesso a relatórios de cliente',
  'manage_clients': 'Gerenciar clientes',
  'delete_campaigns': 'Deletar campanhas',
  'create_adsets': 'Criar conjuntos de anúncios',
  'edit_adsets': 'Editar conjuntos de anúncios',
  'delete_adsets': 'Deletar conjuntos de anúncios',
  'create_ads': 'Criar anúncios',
  'edit_ads': 'Editar anúncios',
  'delete_ads': 'Deletar anúncios',
  'export_data': 'Exportar dados',
  'manage_creatives': 'Gerenciar criativos',
  'upload_creatives': 'Upload de criativos',
  'edit_creatives': 'Editar criativos',
  'delete_creatives': 'Deletar criativos',
  'view_tickets': 'Visualizar tickets',
  'create_tickets': 'Criar tickets',
  'edit_tickets': 'Editar tickets',
  'resolve_tickets': 'Resolver tickets',
  'create_collaborators': 'Criar colaboradores',
  'edit_collaborators': 'Editar colaboradores',
  'delete_collaborators': 'Deletar colaboradores',
  'create_campaigns_whatsapp': 'Criar campanhas WhatsApp',
  'manage_contacts': 'Gerenciar contatos',
  'edit_tasks': 'Editar tarefas',
  'delete_tasks': 'Deletar tarefas',
  'manage_tasks': 'Gerenciar tarefas'
};

export const PERMISSION_GROUPS = {
  'Sistema': ['access_dashboard'],
  'WhatsApp': [
    'access_whatsapp',
    'create_campaigns',
    'edit_campaigns',
    'view_templates',
    'send_messages',
    'view_metrics',
    'create_campaigns_whatsapp',
    'manage_contacts'
  ],
  'Tarefas': [
    'access_tasks',
    'create_tasks',
    'assign_tasks',
    'finalize_tasks',
    'edit_execution_time',
    'edit_tasks',
    'delete_tasks',
    'manage_tasks'
  ],
  'Chamados': [
    'access_calls',
    'create_calls',
    'finalize_calls',
    'link_calls_to_tasks',
    'view_tickets',
    'create_tickets',
    'edit_tickets',
    'resolve_tickets'
  ],
  'Criativos': [
    'access_creatives',
    'create_edit_creatives',
    'approve_creatives',
    'view_change_history',
    'manage_creatives',
    'upload_creatives',
    'edit_creatives',
    'delete_creatives'
  ],
  'Mídia Paga': [
    'access_paid_media',
    'create_campaigns_media',
    'view_metrics_media',
    'delete_campaigns',
    'create_adsets',
    'edit_adsets',
    'delete_adsets',
    'create_ads',
    'edit_ads',
    'delete_ads'
  ],
  'Relatórios': [
    'access_reports',
    'create_automatic_reports',
    'access_client_reports',
    'export_data'
  ],
  'Configurações': [
    'manage_user_settings',
    'manage_collaborators',
    'manage_whatsapp_templates',
    'manage_api_settings',
    'manage_appearance_and_visual_identity',
    'manage_external_integrations',
    'manage_variables_and_pre_configurations',
    'view_billing_settings',
    'view_system_logs',
    'manage_clients',
    'create_collaborators',
    'edit_collaborators',
    'delete_collaborators'
  ]
};
